version: '3'
services:
  redis:
    image: redis
    networks:
      - webapp
  
  webapp:
    image: devops-exercise:latest
    environment:
      REDIS_HOST: redis
    networks:
      - webapp
    ports: 
      - 3000:8080

networks: 
  webapp:
