---

- name: Install Common packages
  hosts: [tag_stage_staging]
  become: yes
  roles:
    - { role: common, tags: ['common'] }
    - { role: geerlingguy.docker, tags: ['docker'] }

- name: Install application stack
  hosts: tag_stage_staging:&tag_component_application
  roles:
    - { role: application, tags: ['application'] }